### ISSUE TITLE
Additional SFML-based engine.

### ISSUE THREAD

**Issue by gamepopper** [Cmdu76/AwesomeCppGameDev#1]
Don't mean to toot my own horn, but I saw a sublist of engines that use SFML2 as a backend and I have my own, called [Vigilante](https://github.com/gamepopper/Vigilante-Game-Framework). It's open source, with additional 3D rendering (using OpenGL+GLEW) and 2D physics support using Chipmunk.

**Comment by Cmdu76** [comment]
Hi !

Your engine was already in my 'to add' list (which is my stars list) :)

Now I need to update everything by hand, and it's just too much time consuming, so I don't do it regularly. I'm currently developping a tool to handle this easily. 

When done, I will have a first pass on my stars list and I will probably add you engine in the list at that time. It will probably take 2-3 weeks of dev for the tool and then the time to finally handle the list !

Thanks for suggesting anyway :)
