### ISSUE TITLE
Pybind11 would be a great addition for Scripting

### ISSUE THREAD

**Issue by NBurley93** [Cmdu76/AwesomeCppGameDev#3]
https://github.com/pybind/pybind11

pybind11 provides an excellent binding for providing two-way communication for C++ and Python 3. My most recent project must utilize python 3 for it's scripting, and this library was fantastic in getting a working embedded interpreter for python running in my C++ app.

**Comment by Cmdu76** [comment]
Hi !

This one will be added to the list, it's impressive and seems very great !

Thanks for sharing ;)
